### ISSUE TITLE
Remove unnecessary content from readme file

### ISSUE THREAD

**Issue by learnwithalfred** [gvgesanto2/microverse-awesome-books#5]
<img width="839" alt="Screenshot 2022-05-31 at 14 19 55" src="https://user-images.githubusercontent.com/34389326/171196325-fd837c67-9912-4135-854e-f226bbf453db.png">

There is no data in the Acknowledgment section

## Possible solution

- If there is no one to acknowledge you can remove the acknowledgment content

**Comment by gvgesanto2** [comment]
## Hi @learnwithalfred 👋,

Thank you for the feedback! This issue was addressed in this PR: https://github.com/gvgesanto2/microverse-awesome-books/pull/7
